//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public decimal id { get; set; }
        public string name { get; set; }
        public string apellido { get; set; }
        public string password { get; set; }
        public string correo { get; set; }
        public System.DateTime date_created { get; set; }
        public decimal StatusId { get; set; }
    
        public virtual StatusUsuario StatusUsuario { get; set; }
    }
}
